//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuomuTila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Berry { get; set; }
        public string Collect { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime Collectdate { get; set; }
        public System.DateTime Addeddate { get; set; }
    }
}
