//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuomuTila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralKnowledge
    {
        public int general_id { get; set; }
        public string Berry { get; set; }
        public string Titleusage { get; set; }
        public string Titlecrowth { get; set; }
        public string Titleknowledge { get; set; }
        public string UsageKnowledge { get; set; }
        public string CrowthKnowledge { get; set; }
        public string HealthInfo { get; set; }
    }
}
