//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuomuTila.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KoskenkorvanLuomutilaEntities3 : DbContext
    {
        public KoskenkorvanLuomutilaEntities3()
            : base("name=KoskenkorvanLuomutilaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Berry> Berries { get; set; }
        public virtual DbSet<GeneralKnowledge> GeneralKnowledges { get; set; }
        public virtual DbSet<Openinghour> Openinghours { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Summerjob> Summerjobs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
