//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuomuTila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Openinghour
    {
        public int day_id { get; set; }
        public string Dayofweek { get; set; }
        public string closingtime { get; set; }
        public string Openingtime { get; set; }
    }
}
