//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuomuTila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Price_id { get; set; }
        public Nullable<double> Price_per_litre { get; set; }
        public string Berry { get; set; }
    }
}
