//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuomuTila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summerjob
    {
        public int Job_id { get; set; }
        public System.DateTime Datesubmitted { get; set; }
        public System.DateTime Startingdate { get; set; }
        public System.DateTime Enddate { get; set; }
        public string Fullname { get; set; }
    }
}
